RSS_FEEDS = {
    "BBC": "http://feeds.bbci.co.uk/news/rss.xml",
    "NYTimes - Home": "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "Wired": "https://www.wired.com/feed/rss",
    "CNBC": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    "The Guardian": "https://www.theguardian.com/world/rss",
    "WSJ": "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "AltPress (Music)": "https://www.altpress.com/feed/",
    "Fortune": "https://fortune.com/feed/fortune-feeds/?id=3230629",
    "NerdWallet": "https://www.nerdwallet.com/blog/feed/",
    "Mashable": "http://feeds.mashable.com/Mashable",
    "The Verge": "https://www.theverge.com/rss/index.xml",
    "Atlas Obscura": "https://www.atlasobscura.com/feeds/latest",
    "Mozilla Hacks": "https://hacks.mozilla.org/feed/",
    "CNET News": "https://www.cnet.com/rss/news/",
    "Inc.": "https://www.inc.com/rss/",
    "NYTimes - Fashion": "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "Bloomberg (YouTube)": "https://www.youtube.com/feeds/videos.xml?user=Bloomberg",
    "Google Blog": "https://blog.google/rss/",
    "Stack Overflow Blog": "https://stackoverflow.blog/feed/",
    "Small Business Trends": "https://feeds2.feedburner.com/SmallBusinessTrends",
    "The Guardian - Travel": "https://www.theguardian.com/uk/travel/rss",
    "Smashing Magazine": "https://www.smashingmagazine.com/feed",
    "NASA": "https://www.nasa.gov/news-release/feed/",
    "Science-Based Medicine": "https://sciencebasedmedicine.org/feed/"
}
