graph LR

    subgraph sub_flow_N1[Flow]
    N2['IngestNewsFromRSS']
    N3['SummarizeNewsArticles']
    N2 --> N3
    N4['GenerateBusinessIdea']
    N3 --> N4
    N5['ConductMarketResearch']
    N4 --> N5
    N6['CompetitorSearchTerm']
    N5 --> N6
    N7['SearchCompetitors']
    N6 --> N7
    N8['FilterCompetitorResults']
    N7 --> N8
    N9['ProjectManagerAgent']
    N8 --> N9
    N10['PitchAgent']
    N9 --> N10
    N11['PushToDatabase']
    N10 --> N11
    end
